### PR TITLE
Add unit tests

### PR DESCRIPTION
**Pull request by noisypigeon**
Test driven development, implementing the tests/expected behaviour first. https://github.com/kornelski/http-cache-semantics/blob/master/test/

- [x] OK HTTP tests.
- [x] Request tests.
- [x] Response tests.
- [x] Vary tests.
- [x] Satisfy tests.
- [x] Revalidate tests.
- [ ] Update tests.

### CODE REVIEW

**Comment by non-binary** [comment]
@zkat @larsgw Hey so I've continued working on implementing the tests and I've ran into my next blocker that I was hoping you could help me with.

The last two set of tests rely heavily on JavaScript`s `Object.assign` (more details here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign and https://github.com/kornelski/http-cache-semantics/blob/master/test/updatetest.js (search for that keyword).

I've done some searching and haven't been able to find any equivalent for Rust. Do you have any guidance for how I can implement something that will do that? I know it's likely possible to do it with just Rust syntax alone but haven't been able to put it together.

Thanks!

**Comment by zkat** [comment]
I think you'll need to define your own data structures here, and use those instead of plain objects (or HashMaps), the way the tests are working.

The general idea of those `Object.assign()` calls is really to create new objects with certain headers, so you'll want to write some utilities to that end. You might want to consider using the [types from the `http` crate](https://docs.rs/http/0.1.19/http/) for your tests, and the respective methods for building `Request`s and `Headers`.

I think you're better off not trying to emulate these tests' particular abstractions, too, so what I would recommend is to write the first test long-form, using the above advice on data structures, and only abstract away when you're actually confident in patterns. There's no shame in copy-pasting when it comes to test code.

Let me know if you need any more help with that, or if anything I wrote is unclear!

**Comment by jameysharp** [comment]
I've added a commit to this PR that updates a few of the tests, and comments out the tests I haven't updated. So `cargo test` builds again, although of course all the tests still fail since we haven't implemented anything yet.

Apparently what we're doing is trying to get the tests all more-or-less correct in this PR before merging anything to `master`, so:

**Anyone who wants to help review and fix up the tests should open pull requests which are based against the `nb/tests` branch, and we can merge those PRs into this one. Please tag me (`@jameysharp`) on each pull request to make sure I see it.**

I see several ways people can help with this:

1. **Rewrite existing tests** to use the Rust-style API instead of the previous JSON-style one that reflected the JavaScript reference implementation's API.

2. **Review tests for correctness**, comparing them against https://github.com/kornelski/http-cache-semantics/tree/master/test and perhaps against [RFC7234](https://httpwg.org/specs/rfc7234.html) and other relevant standards.

3. **Review the public API** for this crate, as it currently stands in this pull request's branch, to see if it makes sense to you or if there are changes you would suggest. If you want to use this crate in some project, it'd be especially helpful to tell us about what you want to do with it.

I intend to work some on each of these, but I get distracted frequently. :sweat_smile: So I'm making the following commitments instead:

- I will review and merge any pull requests I see in a timely fashion.
- I will answer questions posted in this pull request. (I probably have opinions and am happy to share them :sweat_smile:)

**Comment by jameysharp** [comment]
I've been waffling over multiple people's suggestions to go ahead and merge this to master now, and at the moment I'm not sure I want to, for the–maybe silly!–reason that this pull request is a nice central place for discussion about how we're doing this testing work, and if we merge it then we lose our discussion forum. (There's also #4 where the discussion adds a bunch of additional context, so this isn't great either…)

I've never liked this aspect of GitHub but I've never been fully satisfied with any of the alternatives either, so if any of you have a preferred alternative I'm open to just going with it. I think keeping this pull request open is the simplest option right now though.

**Comment by non-binary** [comment]
@jameysharp Has the last two remaining test sections (revalidated and updated) been implemented? Don't have the time/energy rn to look through the diff. If so, then I would say it would be fine to merge into master. We could also start a new GitHub issue that includes this discussion going forward and include important information from this PR in the initial commit. WDYT?

**Comment by jameysharp** [comment]
@non-binary Nope, we haven't even gotten through the API changes for the tests you already did, let alone added the last ones from the JavaScript implementation.

**Comment by shieldo** [comment]
For me the most important thing is at least we have CI running (formatting, tests) in this branch (thanks for rebasing!) and now we've established the rules of the road hopefully we can clear off the tests pretty soon. I expect to have time Friday/ Saturday/ Sunday (I'm in the UK and Thursday is going to be a day of deep existential despair due to elections), and am super keen to get through the remainder of the tests and embark on implementation.

**Comment by non-binary** [comment]
Just want to say thanks for all the hard work y'all. I'd like to get back into contributing to this in the new year. 💕

**Comment by shieldo** [comment]
Do we want to separate these test files out into their own test directory for the sake of organisation? They seem to be largely interested in testing behaviour of the library for different aspects of its responsibilities, rather than assertions on `CachePolicy` methods individually - so it seems arguable they could qualify as outside-in integration tests rather than unit tests per se - and arranging these tests [as per the filesystem schema set out in the Rust book](https://doc.rust-lang.org/book/ch11-03-test-organization.html#integration-tests) seems like it would be a good deal less unwieldy. Thoughts - shall I go ahead and extract the tests out to a `tests/` directory?

**Comment by zkat** [comment]
That sounds like a great idea tbh

**Comment by shieldo** [comment]
@zkat OK thanks - I'll go ahead and PR that!

**Pull request closed without merging**
